[workspace]
authors = ["Aditya Singh <dr.singhaditya@hotmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "scanpy"
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
anndata = ">=0.12.10,<0.13"
cellrank = ">=2.2.0,<3"
celltypist = ">=1.7.1,<2"
gseapy = ">=1.1.12,<2"
harmonypy = ">=0.2.0,<0.3"
ipykernel = ">=7.2.0,<8"
leidenalg = ">=0.11.0,<0.12"
matplotlib-base = ">=3.10.8,<4"
matplotlib-inline = ">=0.2.1,<0.3"
matplotlib-scalebar = ">=0.9.0,<0.10"
matplotlib-venn = ">=1.1.2,<2"
nbclient = ">=0.10.4,<0.11"
nbformat = ">=5.10.4,<6"
numpy = ">=2.4.3,<3"
pandas = ">=2.3.3,<3"
pybiomart = ">=0.2.0,<0.3"
pygam = ">=0.12.0,<0.13"
python-igraph = ">=1.0.0,<2"
scanorama = ">=1.7.4,<2"
scanpy = ">=1.12,<2"
scikit-learn = "<1.8.0"
scipy = ">=1.17.1,<2"
scrublet = ">=0.2.3,<0.3"
scvi-tools = ">=1.4.2,<2"
seaborn = ">=0.13.2,<0.14"

[pypi-dependencies]
quarto-cli = ">=1.9.36, <2"
fa2-modified = ">=0.4, <0.5"
bbknn = ">=1.6.0, <2"
